### ISSUE TITLE
Exception calling ContentTypes.Change(c => c.Icon = "icon-document");

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#11]
The exception seems to have nothing to do with the operation I'm trying to perform.

The following PropertyType aliases from the current ContentType conflict with existing PropertyType aliases: umbracourlname.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: The following PropertyType aliases from the current ContentType conflict with existing PropertyType aliases: umbracourlname.

Source Error: 
```
Line 40: 			// remove all url trackers.
Line 41: 			ContentTypes.Where(c => c.PropertyTypeExists("uRLTracker")).RemoveProperty("uRLTracker");
Line 42: 			ContentTypes.Change(c => c.Icon = "icon-document");
Line 43: 			ContentTypes.Where(c => c.Name == "Home").Change(h => h.Icon = "icon-home");
Line 44: 			ContentTypes.Where(c => c.DefaultTemplate == null).Change(i => i.Icon = "icon-document-dashed-line");
```
Stack Trace: 
```
[Exception: The following PropertyType aliases from the current ContentType conflict with existing PropertyType aliases: umbracourlname.]
   Umbraco.Core.Services.ContentTypeService.ValidateLocked(IContentTypeComposition compositionContentType) +2893
   Umbraco.Core.Services.ContentTypeService.Save(IEnumerable`1 contentTypes, Int32 userId) +321
   uMigrate.Internal.SyntaxImplementations.ContentTypeSetSyntax.Change(Action`1 change) +108
   xyz.Migrations.Migration201502251449.Run() in c:\Dev\XYZ\http\Migrations\uMigrateMigrations.cs:42
   uMigrate.UmbracoMigrationBase.Migrate(IMigrationContext context) +48
   uMigrate.Infrastructure.<>c__DisplayClass6.<RunInternal>b__2(IUmbracoMigration migration) +515
   uMigrate.Internal.InternalExtensions.Migrate(T item, Action`1 action, Func`2 describeItem) +62
```

**Comment by ashmind** [comment]
I think that underlying problem here is that this ContentType is invalid -- so any operation that forces resave on it will fail (whether through uMigrate or other ways).

Try saving it through user interface -- does it produce an issue?

**Comment by Myster** [comment]
Doh, right you are.

**Comment by ashmind** [comment]
Ignore the reference above, typo in commit message.
