### ISSUE TITLE
Feature Request: override naming conventions

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#15]
This is a "nice to have", just to make my code shorter.
It would be good to override the alias naming convention so that this:

    .AddProperty("Main Navigation", "Multi Page Picker", "Menu")

could create a property with an alias 'mainNavigation' rather than 'MainNavigtion', currently I'm doing it like this:

    .AddProperty("mainNavigation", "Multi Page Picker", "Menu", c=>c.Name="Main Navigation")

**Comment by ashmind** [comment]
Yes, I think that would be useful.

**Comment by Myster** [comment]
NB: we have different conventions for different types of alias eg property vs doctype vs contenttype. I think we've followed the umbraco conventions.

**Comment by ashmind** [comment]
@Myster I'm prototyping an approach for this, but it raises a few questions.

1. If you do `AddProperty("Main Navigation")`, would you expect `RemoveProperty("Main Navigation")`? I suppose so, but might be somewhat confusing.
2. Parameter names become confusing: `AddProperty(string alias, ...)` -- not really an `alias`.

**Comment by Myster** [comment]
1. I would expect remove to take just the alias.
2. hmm, can we infer the Name from the alias rather than the other way round? it's a bit harder, but if you know it will fail you can always fall back to: 
`.AddProperty("rssTitle", "Multi Page Picker", "Menu", c=>c.Name="RSS Title")` since it would probably infer the title incorrectly to be Rss Title

**Comment by ashmind** [comment]
@Myster I've considered several options, and all seem either inconsistent (removing/finding would use alias while adding would use name) or challenging to make useful (creating name from alias).

Instead I think I'll add name as a required second parameter -- while it would result in some duplication, it would be much more clear what's actually happening and what's the end result. The only question is the effect on current code -- I'll review and see if there any possibility of existing migrations changing their meaning after this change.

**Comment by Myster** [comment]
I don't know, that gains much over what we currently have, we could just
stick with that. I guess there's already too many string params to make it
optional

**Comment by ashmind** [comment]
@Myster It doesn't gain _too_ much, but the more I use it, the more I feel I should have done it that way from the start. I'll just obsolete alternatives and remove them later on.

**Comment by Myster** [comment]
One thing about moving the API forward: .... I tend to keep migrations round after I have deployed to live (I don't know if this is a good practice or not). 

If I subsequently do a nuget `update-package uMigrate` for a given project that has old migrations (code run once a year ago and never again) It could be quite anoying to have to fix code that now does not compile (and that I don't actually need to run). I suppose I would just delete them, and lose any value they may have had (or not had) ... just thinking out loud :-)

**Comment by ashmind** [comment]
@Myster Yes I'm actually thought about this point. I'll try to preserve compatibility where possible (e.g. this release should be compatible unless I made a mistake), however APIs marked [Obsolete] will eventually be removed -- hopefully by that time migrations using those APIs will not be relevant.
