### ISSUE TITLE
How is sorting properties/tabs supposed to work?

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#18]
Below is how I'm doing it, which is reasonably elegant, but it would be nice to have the CustomSort method build in  so that I could call it like this:
`.SortProperties("Content", "l,i,f,t")`
or if you want to be verbose
`.SortProperties("Content", "link,image,fromDate,toDate")`
instead of
`.SortProperties("Content", (p1, p2) => CustomSort(p1, p2, "l,i,f,t"))`

```
public class Migration201503191658RotatorItem : UmbracoMigrationBase
{
	public override string Name
	{
		get { return "Setup Rotator Item Content Type"; }
	}

	protected override void Run()
	{
		ContentTypes.Where(c => c.Name == "Rotator Item")
			.RemoveProperty("displayTitle")
			.RemoveProperty("imageAltText")
			.RemoveProperty("displayDate")
			.ChangeProperty("link", p =>
			{
				p.Description = "Please add one link";
				p.Mandatory = true;
			})
			.MoveProperty("link", "Content")
			.MoveProperty("image", "Content")
			.AddProperty("fromDate", "Date Picker with time", "Content", p => p.Name = "From Date")
			.AddProperty("toDate", "Date Picker with time", "Content", p => p.Name = "To Date")
			.RemovePropertyGroup("Details")
			.SortProperties("Content", (p1, p2) => CustomSort(p1, p2, "l,i,f,t"))
			;
	}

	private int CustomSort(PropertyType p1, PropertyType p2, string order)
	{
		var orderMap = order.Split(',');
		foreach (var start in orderMap)
		{
			if (p1.Alias.StartsWith(start))
				return -1;
			if (p2.Alias.StartsWith(start))
				return +1;
		}
		return 0;
	}
}
```

**Comment by Myster** [comment]
Duh, I just realised I can just create that syntax myself with extension methods like so:
But I still wonder if this should be a built in option, I haven't wanted to sort any other way myself. yet. ;-)

```
public static IContentTypeSetSyntax SortProperties(this IContentTypeSetSyntax syntax, string propertrGroupName, string arbitrarySortOrder)
{
	return syntax.SortProperties(propertrGroupName, (p1, p2) => CustomSort(p1, p2, arbitrarySortOrder));
}

public static IContentTypeSetSyntax SortPropertyGroups(this IContentTypeSetSyntax syntax, string arbitrarySortOrder)
{
	return syntax.SortPropertyGroups((p1, p2) => CustomSort(p1, p2, arbitrarySortOrder));
}
```

**Comment by ashmind** [comment]
Thanks, this makes sense. I'll probably go for `params string[]` instead of splitting inside.

**Comment by Myster** [comment]
I haven't got my head around the internal architecture of uMigrate, but If you point out where I should put those methods I can do a pull request. which you'll probably need to fix up. I have a few unit tests too, and an updated compare to deal with items starting with the same string

**Comment by ashmind** [comment]
For this one I decided to provide a list of full names instead of prefixes as it has less chance to break if some prefixes are ambiguous (and no complexity needed to resolve ambiguity).
