### ISSUE TITLE
ChangeAllPropertyValues does not publish items pending publication

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#22]
It makes sense that we don't publish these items, but is there a way round this issue?
Perhaps the lot could spit out a list of such items we could manually follow up.

**Comment by ashmind** [comment]
Thanks -- I'll need to research why.

**Comment by Myster** [comment]
I assume because you have unpublished changes that the author may not intend to be published, and if we change a property value in a migration we don't want to publish other author changes by mistake.

**Comment by Myster** [comment]
Just to clarify, my original title "ChangeAllPropertyValues misses items pending publication" is not acurate, what really happinging is "ChangeAllPropertyValues does not publish items pending publication" (I'll change the title) which is not nearly as bad, but it can cause the site to break since those fixed property values do (in my case) need to be published.

**Comment by ashmind** [comment]
Ah. That's by design -- however I'll look into providing a way to publish all changed items if needed.

**Comment by Myster** [comment]
I think there should be more context available within the "ChangeAllPropertyValues" method to enable many more scenarios.

What I would find most useful is having the IContent  object which is being processed (with Id), then I can work out if it is published, and I could add it to a log for review, or a list to publish.

Additionally a built in mechanism so I didn't have to manually publish that list.... so, as you say within my method it would be good if I could decide on a case by case basis based on the property and it's IContent object whether I should publish an unpublished content item.

The default behaviour you have now is definitely the best default behaviour though :-)

**Comment by Myster** [comment]
I've just had this issue bite again, I did a migration and all the tests didn't account for pending edits. The website failed spectacularly when the template tried to render the data in the old format. (Do you have any advice on how to mitigate / deal with this?)

**Comment by ashmind** [comment]
@Myster Sure, I can provide a list of changed-but-unpublished items so you can publish them, or maybe an event on save without publish. I'll look into it in the next version.

**Comment by ashmind** [comment]
I'll follow up in #41.
