### ISSUE TITLE
Feature Request: Update uMigrate to work with Umbraco 6.

### ISSUE THREAD

**Issue by SelectUX** [AffinityID/uMigrate#23]
Hi,

I have used uMigrate for my u7 projects but I work on a lot of old u6 projects so be great if it worked for those too. Do you have any idea how much work might be involved in getting it working with u6? 

It could be something we could attempt depending on the time required and complexity of the task.

Cheers, Paul

**Comment by ashmind** [comment]
I'm not sure. It might be pretty easy: as far as I remember most of U7 changes were in UI layers.
I suggest just trying to compile it with U6 -- if it compiles, I would expect most of the things to work right away, so you could estimate effort based on the number of compiler errors.

Unfortunately it is currently lacking in automated tests, so there is no full guarantee.

**Comment by SelectUX** [comment]
Thanks for getting back to me. I'll try and find some time to look at this, I'll let you know how I get on if I do get some spare time.
