### ISSUE TITLE
Suggestion: Write log info to debug listeners 

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#24]
I've had occasion where it would come in handy if the log messages were written to the debug listeners via `Debug.WriteLine(...)`.

**Comment by ashmind** [comment]
@Myster uMigrate is using log4net, so it should be possible to configure debug logging through log4net config -- can you check and see if it would be good enough?

**Comment by Myster** [comment]
Ahhh, the messages I'd like to see are the same messages that I see when I open the 'Migrations' tree in the umbraco developer section. I don't think those are going to log4net.

For other's wondering: you can get all the log4net messages in Debug View by doing this:
edit the umbraco log4net config here: `/config/log4net.config`
add these parts.
```
<root>
    ...
    <appender-ref ref="OutputDebugStringAppender" />
</root>
```
```
  <appender name="OutputDebugStringAppender" type="log4net.Appender.OutputDebugStringAppender" >
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="[Umbraco] %date [%thread] %-5level %logger - %message%newline" />
    </layout>
  </appender>
```
more: http://tedgustaf.com/blog/2011/10/log4net-messages-in-real-time-with-debugview/

**Comment by ashmind** [comment]
> Ahhh, the messages I'd like to see are the same messages that I see when I open the 'Migrations' tree in the umbraco developer section. I don't think those are going to log4net.

They should though -- if you check the implementation of logger at https://github.com/AffinityID/uMigrate/blob/master/uMigrate/Internal/MigrationLogger.cs, it logs both to TextWriter (which is used for the UI log) and log4net.

Maybe your log4net verbosity level doesn't include DEBUG messages?

**Comment by Myster** [comment]
doh yep that was it.
