### ISSUE TITLE
Cannot move property to 'Properties' tab

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#25]
I tried calling `MoveProperty(...)`with empty string as the newPropertyGroupName and I tried with "Properties" as the newPropertyGroupName, but in both cases it created a new propertyGroup (aka "Tab").
Using null, causes an exception (as well as the param having attribute [NotNull] )

**Comment by Myster** [comment]
I can't figure out how to do it with the umbraco API so I posted the question here: https://our.umbraco.org/forum/developers/api-questions//66763-how-do-i-programatically-move-a-property-to-the-default-property-group

**Comment by ashmind** [comment]
Thanks for the research. I'll consider adding a workaround for [U4-6832](http://issues.umbraco.org/issue/U4-6832) if we get to this area.
