### ISSUE TITLE
ContentTypes ... AddChild("ChildAlias") does inherit contentType properties.

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#26]
This code

				ContentTypes.Where(c => c.Name == "Page")
					.AddChild("AtoZofServices");
Produces a ContentType with no inherited properties.
Whereas
This code:

				var service = ApplicationContext.Current.Services.ContentTypeService;
				var aToZ = new ContentType(service.GetContentType("Page"), "AtoZofServices");
				service.Save(aToZ);
Produces a ContentType with properties inherited from "Page"

**Comment by Myster** [comment]
it appears this line: 
https://github.com/AffinityID/uMigrate/blob/fa6f1576a2c302ee587b57ae22d84b6ca66a06e1/uMigrate/Internal/SyntaxImplementations/ContentTypeSetSyntax.cs#L41

The umbrco src has this comment on the constructor used: "Only use this for creating ContentTypes at the root (with ParentId -1)."

It should use a different constructor that takes an IContentType, (as in my example above, or the one without the alias), the comments on which say: "Use this to ensure inheritance from parent."

**Comment by Myster** [comment]
Submitted pull req.
NB: I also created an umbraco issue to remove the constructor you used from umbraco 
http://issues.umbraco.org/issue/U4-6833

**Comment by ashmind** [comment]
Thanks! Closing since this should be fixed by #28.
