### ISSUE TITLE
Provide some way to react to pending edits during the migration process

### ISSUE THREAD

**Issue by ashmind** [AffinityID/uMigrate#41]
By default, pending edits are not published during the migration -- however that might cause published state not to be migrated, causing site issues.

**Comment by ashmind** [comment]
Aside from better diagnostics, it might be useful to actually change the published version even if a newer one exists -- needs some research.

**Comment by ashmind** [comment]
@Myster I implemented an approach here, try
```csharp
UmbracoMigrator.RunStarting += (_, c) => {
    c.Configuration.ContentSavePublish = new SaveLatestAndSavePublishedIfNotLatest();
};
```

That should be done in `ApplicationStarting` or `ApplicationInitialized`, otherwise might be too late. You can do custom strategies as well.

Let me know if you run into any issues.

**Comment by Myster** [comment]
Cool, thanks heaps. I'll try and give this a good test next time we do this kind of migration.
