### ISSUE TITLE
How is version ordering determined?

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#5]
If I create migrations named like so, and run each as it's created I will get them run in this order.
```
MyMigration1
MyMigration3
BobMigration10
MyMigration11
BobMigration12
MyMigration2
MyMigration201502251413
```
Then if I deploy them all to another environment which order will they run?
Perhaps just a little explanation in the documentation.

I did note that I'd raise an exception if I had both `MyMigration10` and `BobMigration10`

**Comment by ashmind** [comment]
Added some docs, let me know if this is good enough:
https://github.com/AffinityID/uMigrate/wiki/Versioning

**Comment by Myster** [comment]
Perfect. May I suggest adding a link from the readme.md to the wiki for people like me who don't think to check the wiki.

**Comment by ashmind** [comment]
Good point, done.
