### ISSUE TITLE
Anonymous types for pre values

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#8]
Feature suggestion: Support anonymous types for pre values like so:

	DataTypes.Where(d => d.Name == "Article Single Picker").SetPreValues(
		new
		{
			startNode = new { type = "content", id = "1104" },
			filter = "GeneralArticle,CommunityDirectoryArticle",
			maxNumber = 1,
		});

**Comment by ashmind** [comment]
But isn't it already supported?

**Comment by Myster** [comment]
I get: 
```
[InvalidOperationException: The current pre-value collection is array based, use the PreValuesAsArray property instead]
   Umbraco.Core.Models.PreValueCollection.get_PreValuesAsDictionary() +89
   uMigrate.Internal.SyntaxImplementations.DataTypeSetSyntax.SetPreValueInternal(IDataTypeDefinition dataType, PreValueCollection preValues, String name, String newValue) +78
   uMigrate.Internal.SyntaxImplementations.<>c__DisplayClass9.<SetPreValues>b__8(PreValueCollection collection, IDataTypeDefinition dataType) +265
   uMigrate.Internal.SyntaxImplementations.<>c__DisplayClass15.<ChangePreValues>b__14(IDataTypeDefinition dataType) +134
   uMigrate.Internal.InternalExtensions.Migrate(T item, Action`1 action, Func`2 describeItem) +62
```

**Comment by ashmind** [comment]
Ah, that one. I believe U7 is expected to never have array-based prevalues, but since I hit the same issue on e.g. improperly upgraded systems, I'll add handling for it in the future.

**Comment by Myster** [comment]
I did just do an upgrade, do you have any insight about what could have been 'improper' about it? Just wondering if I'll hit other issues.

**Comment by ashmind** [comment]
We hit a lot of small things, but they were really specific to the system -- hard to remember any generic ones.

This one is about prevalue table having null/empty alias. I believe that in U7 even previously array-based prevalue lists are expected to have at least `"0"`,`"1"` etc as an alias. Without that both uMigrate and e.g. uSync fail -- but we can and should handle it in future uMigrate when you just want to overwrite those.

**Comment by Myster** [comment]
ok, as a work-around I'm just setting the prevalues to blank before setting them with the fluent api.

    ApplicationContext.Current.Services.DataTypeService.SavePreValues(dt.Id, new Dictionary<string, PreValue>());
